"""add_total_discount_to_deliveries

Revision ID: 2b84e36b1f70
Revises: 
Create Date: 2024-03-19 10:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect
from migrations.alembic_utils import safe_add_column, safe_create_table, safe_create_index


# revision identifiers, used by Alembic.
revision: str = '2b84e36b1f70'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    conn = op.get_bind()
    inspector = inspect(conn)
    columns = [col['name'] for col in inspector.get_columns('deliveries')]
    if 'total_discount' not in columns:
        safe_add_column(op, 'deliveries', sa.Column('total_discount', sa.Float(), nullable=True, server_default='0.0'))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deliveries', 'total_discount')
    # ### end Alembic commands ###
