"""Ajout colonne total_price à multi_destination_deliveries

Revision ID: 4389212cf6e7
Revises: dd90c6655591
Create Date: 2025-06-24 13:29:35.186359

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4389212cf6e7'
down_revision = 'dd90c6655591'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
