"""add_cashback_earned_to_deliveries

Revision ID: 5ab642752a6f
Revises: 251709e76da3
Create Date: 2024-03-19 10:30:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ab642752a6f'
down_revision: Union[str, None] = '251709e76da3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deliveries', sa.Column('cashback_earned', sa.Float(), nullable=True, server_default='0.0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deliveries', 'cashback_earned')
    # ### end Alembic commands ###
