import { createApp } from "vue"
import { createPinia } from "pinia"
import App from "./App.vue"
import router from "./router"
import "./assets/css/main.css"
import { library } from "@fortawesome/fontawesome-svg-core"
import { FontAwesomeIcon } from "@fortawesome/vue-fontawesome"
import {
  faUser,
  faLock,
  faEnvelope,
  faPhone,
  faHome,
  faTruck,
  faBox,
  faMoneyBill,
  faCog,
  faSignOutAlt,
  faBell,
  faSearch,
  faPlus,
  faMinus,
  faEdit,
  faTrash,
  faEye,
  faCheck,
  faTimes,
  faBan,
  faChevronLeft,
  faChevronRight,
  faChevronDown,
  faChevronUp,
  faSync,
  faFilter,
  faStar,
  faMapMarkerAlt,
  faCalendar,
  faClock,
  faExclamationTriangle,
  faInfoCircle,
  faCheckCircle,
  faTimesCircle,
  faArrowUp,
  faArrowDown,
  faMinus as faMinusHorizontal,
  faMotorcycle,
  faCar,
  faBicycle,
  faWalking,
  faTruckMoving,
  faCrosshairs,
  faDrawPolygon,
  faUpload,
  faEraser,
  faChartLine,
  faChartBar,
  faChartPie,
  faCircleNotch,
  faPaperPlane,
  faCopy,
  faRedo,
  faMobileAlt,
  faSms,
  faComment,
  faUniversity,
  faIdCard,
  faFilePdf,
  faDownload,
  faUsers,
  faUserPlus,
  faUserMinus,
  faUserCheck,
  faUserTimes,
  faUserCog,
  faUserShield,
  faUserTag,
  faUserClock,
  faUserEdit,
  faMoneyBillWave,
  faStore,
  faStoreAlt,
  faBuilding,
  faCity,
  faMapMarkedAlt,
  faRoute,
  faRoad,
  faStreetView,
  faCompass,
  faDirections,
  faLocationArrow,
  faShippingFast,
  faBoxOpen,
  faClipboardList,
  faClipboardCheck,
  faListAlt,
  faReceipt,
  faFileInvoiceDollar,
  faFileContract,
  faFileSignature,
  faFileAlt,
  faFileCode,
  faFileArchive,
  faFileCsv,
  faFileExcel,
  faFilePowerpoint,
  faFileWord,
  faFileImage,
  faFileVideo,
  faFileAudio,
  faFilePdf as faFilePdfSolid,
  faFileDownload,
  faFileUpload,
  faFileImport,
  faFileExport,
  faFileSearch,
  faFileMedical,
  faFileInvoice,
  faFileSignature as faFileSignatureSolid,
  faFileContract as faFileContractSolid,
  faFileAlt as faFileAltSolid,
  faFileCode as faFileCodeSolid,
  faFileArchive as faFileArchiveSolid,
  faFileCsv as faFileCsvSolid,
  faFileExcel as faFileExcelSolid,
  faFilePowerpoint as faFilePowerpointSolid,
  faFileWord as faFileWordSolid,
  faFileImage as faFileImageSolid,
  faFileVideo as faFileVideoSolid,
  faFileAudio as faFileAudioSolid,
  faFileDownload as faFileDownloadSolid,
  faFileUpload as faFileUploadSolid,
  faFileImport as faFileImportSolid,
  faFileExport as faFileExportSolid,
  faFileSearch as faFileSearchSolid,
  faFileMedical as faFileMedicalSolid,
  faFileInvoice as faFileInvoiceSolid,
} from "@fortawesome/free-solid-svg-icons"

// Ajouter les icônes à la bibliothèque
library.add(
  faUser,
  faLock,
  faEnvelope,
  faPhone,
  faHome,
  faTruck,
  faBox,
  faMoneyBill,
  faCog,
  faSignOutAlt,
  faBell,
  faSearch,
  faPlus,
  faMinus,
  faEdit,
  faTrash,
  faEye,
  faCheck,
  faTimes,
  faBan,
  faChevronLeft,
  faChevronRight,
  faChevronDown,
  faChevronUp,
  faSync,
  faFilter,
  faStar,
  faMapMarkerAlt,
  faCalendar,
  faClock,
  faExclamationTriangle,
  faInfoCircle,
  faCheckCircle,
  faTimesCircle,
  faArrowUp,
  faArrowDown,
  faMinusHorizontal,
  faMotorcycle,
  faCar,
  faBicycle,
  faWalking,
  faTruckMoving,
  faCrosshairs,
  faDrawPolygon,
  faUpload,
  faEraser,
  faChartLine,
  faChartBar,
  faChartPie,
  faCircleNotch,
  faPaperPlane,
  faCopy,
  faRedo,
  faMobileAlt,
  faSms,
  faComment,
  faUniversity,
  faIdCard,
  faFilePdf,
  faDownload,
  faUsers,
  faUserPlus,
  faUserMinus,
  faUserCheck,
  faUserTimes,
  faUserCog,
  faUserShield,
  faUserTag,
  faUserClock,
  faUserEdit,
  faMoneyBillWave,
  faStore,
  faStoreAlt,
  faBuilding,
  faCity,
  faMapMarkedAlt,
  faRoute,
  faRoad,
  faStreetView,
  faCompass,
  faDirections,
  faLocationArrow,
  faShippingFast,
  faBoxOpen,
  faClipboardList,
  faClipboardCheck,
  faListAlt,
  faReceipt,
  faFileInvoiceDollar,
  faFileContract,
  faFileSignature,
  faFileAlt,
  faFileCode,
  faFileArchive,
  faFileCsv,
  faFileExcel,
  faFilePowerpoint,
  faFileWord,
  faFileImage,
  faFileVideo,
  faFileAudio,
  faFilePdfSolid,
  faFileDownload,
  faFileUpload,
  faFileImport,
  faFileExport,
  faFileSearch,
  faFileMedical,
  faFileInvoice,
  faFileSignatureSolid,
  faFileContractSolid,
  faFileAltSolid,
  faFileCodeSolid,
  faFileArchiveSolid,
  faFileCsvSolid,
  faFileExcelSolid,
  faFilePowerpointSolid,
  faFileWordSolid,
  faFileImageSolid,
  faFileVideoSolid,
  faFileAudioSolid,
  faFileDownloadSolid,
  faFileUploadSolid,
  faFileImportSolid,
  faFileExportSolid,
  faFileSearchSolid,
  faFileMedicalSolid,
  faFileInvoiceSolid,
)

const app = createApp(App)

app.use(createPinia())
app.use(router)
app.component("font-awesome-icon", FontAwesomeIcon)

app.mount("#app")
