/* eslint-disable prettier/prettier */
import { createApp } from "vue"
import { createPinia } from "pinia"
import App from "./App.vue"
import router from "./router"
import Toast from "vue-toastification"
import "vue-toastification/dist/index.css"
import "./../assets/css/main.css"
import { library } from "@fortawesome/fontawesome-svg-core"
import { FontAwesomeIcon } from "@fortawesome/vue-fontawesome"
import {
  faUser,
  faLock,
  faEnvelope,
  faPhone,
  faHome,
  faTruck,
  faBox,
  faMoneyBill,
  faCog,
  faSignOutAlt,
  faBell,
  faSearch,
  faPlus,
  faMinus,
  faEdit,
  faTrash,
  faEye,
  faCheck,
  faTimes,
  faBan,
  faChevronLeft,
  faChevronRight,
  faChevronDown,
  faChevronUp,
  faSync,
  faFilter,
  faStar,
  faMapMarkerAlt,
  faCalendar,
  faClock,
  faExclamationTriangle,
  faArrowLeft,
  faInfoCircle,
  faCheckCircle,
  faTimesCircle,
  faArrowUp,
  faArrowDown,
  faMinus as faMinusHorizontal,
  faMotorcycle,
  faCar,
  faBicycle,
  faWalking,
  faTruckMoving,
  faCrosshairs,
  faDrawPolygon,
  faUpload,
  faEraser,
  faChartLine,
  faChartBar,
  faChartPie,
  faCircleNotch,
  faPaperPlane,
  faCopy,
  faRedo,
  faMobileAlt,
  faSms,
  faComment,
  faUniversity,
  faIdCard,
  faFilePdf,
  faDownload,
  faUsers,
  faUserPlus,
  faUserMinus,
  faUserCheck,
  faUserTimes,
  faUserCog,
  faUserShield,
  faUserTag,
  faUserClock,
  faUserEdit,
  faMoneyBillWave,
  faStore,
  faStoreAlt,
  faBuilding,
  faCity,
  faMapMarkedAlt,
  faRoute,
  faRoad,
  faStreetView,
  faCompass,
  faDirections,
  faLocationArrow,
  faShippingFast,
  faBoxOpen,
  faClipboardList,
  faClipboardCheck,
  faListAlt,
  faReceipt,
  faFileInvoiceDollar,
  faFileContract,
  faFileSignature,
  faFileAlt,
  faFileCode,
  faFileArchive,
  faFileCsv,
  faFileExcel,
  faFilePowerpoint,
  faFileWord,
  faFileImage,
  faFileVideo,
  faFileAudio,
  faFilePdf as faFilePdfSolid,
  faFileDownload,
  faFileUpload,
  faFileImport,
  faFileExport,
  faFileMedical,
  faFileInvoice,
  faFileSignature as faFileSignatureSolid,
  faFileContract as faFileContractSolid,
  faFileAlt as faFileAltSolid,
  faFileCode as faFileCodeSolid,
  faFileArchive as faFileArchiveSolid,
  faFileCsv as faFileCsvSolid,
  faFileExcel as faFileExcelSolid,
  faFilePowerpoint as faFilePowerpointSolid,
  faFileWord as faFileWordSolid,
  faFileImage as faFileImageSolid,
  faFileVideo as faFileVideoSolid,
  faFileAudio as faFileAudioSolid,
  faFileDownload as faFileDownloadSolid,
  faFileUpload as faFileUploadSolid,
  faFileImport as faFileImportSolid,
  faFileExport as faFileExportSolid,
  faFileMedical as faFileMedicalSolid,
  faFileInvoice as faFileInvoiceSolid,
} from "@fortawesome/free-solid-svg-icons"
import { initErrorHandler } from "./utils/errorHandler"

// Add all icons to the library
library.add(
  faUser, faLock, faEnvelope, faPhone, faHome, faTruck, faBox, faMoneyBill, 
  faCog, faSignOutAlt, faBell, faSearch, faPlus, faMinus, faEdit, faTrash, 
  faEye, faCheck, faTimes, faBan, faChevronLeft, faChevronRight, faChevronDown, 
  faChevronUp, faSync, faFilter, faStar, faMapMarkerAlt, faCalendar, faClock,
  faExclamationTriangle, faInfoCircle, faCheckCircle, faTimesCircle, faArrowUp, 
  faArrowDown, faArrowLeft, faMinusHorizontal, faMotorcycle, faCar, faBicycle, faWalking,
  faTruckMoving, faCrosshairs, faDrawPolygon, faUpload, faEraser, faChartLine,
  faChartBar, faChartPie, faCircleNotch, faPaperPlane, faCopy, faRedo, faMobileAlt,
  faSms, faComment, faUniversity, faIdCard, faFilePdf, faDownload, faUsers,
  faUserPlus, faUserMinus, faUserCheck, faUserTimes, faUserCog, faUserShield,
  faUserTag, faUserClock, faUserEdit, faMoneyBillWave, faStore, faStoreAlt,
  faBuilding, faCity, faMapMarkedAlt, faRoute, faRoad, faStreetView, faCompass,
  faDirections, faLocationArrow, faShippingFast, faBoxOpen, faClipboardList,
  faClipboardCheck, faListAlt, faReceipt, faFileInvoiceDollar, faFileContract,
  faFileSignature, faFileAlt, faFileCode, faFileArchive, faFileCsv, faFileExcel,
  faFilePowerpoint, faFileWord, faFileImage, faFileVideo, faFileAudio, faFilePdfSolid,
  faFileDownload, faFileUpload, faFileImport, faFileExport, faFileMedical, faFileInvoice,
  faFileSignatureSolid, faFileContractSolid, faFileAltSolid, faFileCodeSolid,
  faFileArchiveSolid, faFileCsvSolid, faFileExcelSolid, faFilePowerpointSolid,
  faFileWordSolid, faFileImageSolid, faFileVideoSolid, faFileAudioSolid,
  faFileDownloadSolid, faFileUploadSolid, faFileImportSolid, faFileExportSolid,
  faFileMedicalSolid, faFileInvoiceSolid
)

const app = createApp(App)
const pinia = createPinia()

app.use(pinia)
app.use(router)
app.use(Toast, {
  position: "top-right",
  timeout: 5000,
  closeOnClick: true,
  pauseOnFocusLoss: true,
  pauseOnHover: true,
  draggable: true,
  draggablePercent: 0.6,
  showCloseButtonOnHover: false,
  hideProgressBar: true,
  closeButton: "button",
  icon: true,
  rtl: false
})
app.component("font-awesome-icon", FontAwesomeIcon)

// Initialiser le gestionnaire d'erreurs global avec l'instance de l'application
initErrorHandler(app)

app.mount("#app")
